---
# Source: api/templates/app.yaml
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: "default"
  labels:
    app.kubernetes.io/name: api
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/instance: api
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
---
# Source: api/templates/app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: "default"
  labels:
    app.kubernetes.io/name: api
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/instance: api
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        helm.sh/revision: "1"
      labels:
        app.kubernetes.io/name: api
        helm.sh/chart: api-0.1.0
        app.kubernetes.io/instance: api
        app.kubernetes.io/managed-by: Helm
    spec:
      restartPolicy: Always
      containers:
        - name: api
          image: docker.io/matanyal/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits: {}
            requests: {}      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: api
                    app.kubernetes.io/instance: api
                topologyKey: kubernetes.io/hostname
              weight: 1
      serviceAccountName: default
